config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats do
    resources :bookings, only: %i[create new]
  end
  resources :bookings, only: %i[index destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  validates :check_in, presence: true
  validates :check_out, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :bookings
  validates :address, presence: true
  validates :name, presence: true
  validates :text, presence: true
  validates :price, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flat = Flat.find(params[:flat_id])
    @booking.user = User.new({name:"Eleanor Dubron"})
    @booking.save!
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end
  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flats, only: %i[show edit update destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flats_params)
    @flat.save
    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(flats_params)
    redirect_to flat_path
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flats_params
    params.require(:flat).permit(:name, :address, :price, :text)
  end

  def set_flats
    @flat = Flat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/bookings/index.html.erb
<%= link_to "retour", flats_path, class:"button-black-yellow" %>
<div>
  <div class="title-bookings">
    <h1>My bookings 🚩</h1>
  </div>
  <div href="#" class="text-bookings">
    <% @bookings.each do |booking| %>
      <li><%= link_to flat_path(booking.flat.id) do %></li>
        <strong><%= booking.flat.name %></strong>
        📆Check-In<%= booking.check_in %>
        📅Check-Out<%= booking.check_out %>
        💲Amount <%= booking.flat.price %>€ /night
      <% end %>
      <div class="button-cancel-bookings">
        <%= link_to "cancel booking", booking_path(booking), class:"button-black-yellow", data: {turbo_method: :delete, turbo_confirm:"Are you sure ?"}%>
      </div>
    <% end %>
  </div>




</div>

app/views/bookings/new.html.erb
<%= link_to "retour", flats_path, class:"btn btn-primary" %>

<div class="form">
  <div class="title-form" >
    <h1>Make your Book📅</h1>
  </div>
  <div class="form-input">
    <%= simple_form_for [@flat, @booking], url: flat_bookings_path, method: :post do |f| %>
              <%= f.input :check_in, html5: true, label: "Check-in" %>
              <%= f.input :check_out, html5: true, label: "Checkout" %>
              <%= f.submit "Confirm", class:"button-black-yellow" %>
    <% end %>
  </div>
</div>

app/views/flats/edit.html.erb
<h1>Update this Flat 🏠</h1>
<div>
  <%= simple_form_for @flat do |f| %>
            <%= f.input :name, html5: true, label: "Name" %>
            <%= f.input :text, html5: true, label: "Description" %>
            <%= f.input :address, html5: true, label: "Address" %>
            <%= f.input :price, html5: true, label: "Price" %>
            <%= f.submit "Update", class:"button-black-yellow" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="title-index-cards">
  <h1>Flats to rent</h1>
</div>

<div class="buttons-index-cards">
  <%= link_to "Add an offer", new_flat_path, class:"button-black-yellow" %>
  <%= link_to "All my booking", bookings_path, class:"button-black-yellow" %>
</div>

<div id="container">
  <% @flats.each do |flat| %>
    <div class="cards-index-global">
      <div class="image-cards">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      </div>
      <div class="card-details">
        <%= link_to flat_path(flat) do %>
          <strong><%= flat.name %></strong>
          Description:<%= flat.text %>
          Address:<%= flat.address %>
          Price:<%= flat.price %>€ /night
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= link_to "retour", flats_path, class:"btn btn-primary" %>

<div class="form">
  <div class="title-form" >
    <h1>Your new offer 🚩</h1>
  </div>
  <div class="form-input">
    <%= simple_form_for @flat do |f| %>
        <%= f.input :name, html5: true, label: "Name" %>
        <%= f.input :text, html5: true, label: "Description" %>
        <%= f.input :address, html5: true, label: "Address" %>
        <%= f.input :price, html5: true, label: "Price" %>
        <%= f.submit "Create", class:"button-black-yellow" %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<%= link_to "go back", flats_path, class:"button-black-yellow" %>
<div class="card-show">
  <div class="card-show-infos">
    <div class="flat-title">
      <%= @flat.name %>
    </div>
      <div class="infos-show-flats">
        <div>
          📍<%= @flat.address %>
        </div>
        <div>
          💲<%= @flat.price %>
        </div>
        <div>
          🏠<%= @flat.text %>
        </div>
      </div>
  </div>
</div>
    <div class="shows-buttons">
      <%= link_to "update", edit_flat_path, class:"button-black-yellow" %>
      <%= link_to "Book",  new_flat_booking_path(@flat), class:"button-black-yellow" %>
      <%= link_to "delete", flat_path, class:"button-black-yellow", data: {turbo_method: :delete, turbo_confirm:"Are you sure?"} %>
    </div>
  <div class="bookings-cancel">
    <p class="title-already-book">Already booked on:</p>
    <% @flat.bookings.each do |booking| %>
      <div class="booking-infos">
        <strong>from</strong><%= booking.check_in %><strong>until</strong> <%= booking.check_out %>
        <div class="button-cancel">
          <%= link_to "cancel booking", booking_path(booking), class:"button-black-yellow", data: {turbo_method: :delete, turbo_confirm:"Are you sure ?"}%>
        </div>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
    <div>
    
    </div>
      <div>
          <%= link_to flats_path do %>
          <%= image_tag "drupadi-logo-crop.png", class:"navbar-brand-img"%>
          <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbar-right">
        <%= link_to "Add an offer", new_flat_path, class:"navbar-right" %>
        <%= link_to "All my booking", bookings_path, class:"navbar-right" %>
      </div>
    </div>
  </div>

    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<%= image_tag "sticker-drupadi.png", class:"image-home"%>
<%= link_to 'Discover', flats_path, class: "button-black-yellow", id:"home-button"%>